USE [2.4 SEM 12]
CREATE TABLE LOCALIDAD(
COD_LOCALIDAD INT PRIMARY KEY,
NOMBRE varchar(50) NOT NULL,
);
create table PUB(
COD_PUB varchar(50) not null primary key,
NOMBRE varchar(50) not null,
LICENCIA_FISCAL varchar(50) not null,
DOMICILIO varchar(50),
FECHA_APERTURA DATE NOT NULL,
HORARIO varchar(50) CHECK (HORARIO IN ('HOR1', 'HOR2' , 'HOR3')),
COD_LOCALIDAD INT REFERENCES LOCALIDAD(COD_LOCALIDAD) ,
);

CREATE TABLE TITULAR(
DNI_TITULAR VARCHAR(50) NOT NULL PRIMARY KEY,
NOMBRE varchar(50) NOT NULL,
DOMICILIO varchar(50),
COD_PUB varchar(50) REFERENCES PUB(COD_PUB)
);

CREATE TABLE EMPLEADO(
DNI_EMPLEADO varchar(50) NOT NULL PRIMARY KEY,
NOMBRE varchar(50) NOT NULL,
DOMICILIO varchar(50)
);

CREATE TABLE EXISTENCIAS (
COD_ARTICULO varchar(50) NOT NULL PRIMARY KEY,
NOMBRE varchar(50) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO INT CHECK(PRECIO>0),
COD_PUB varchar(50) REFERENCES PUB(COD_PUB)
);


CREATE TABLE PUB_EMPLEADO(
COD_PUB varchar(50) REFERENCES PUB(COD_PUB),
DNI_EMPLEADO VARCHAR(50) REFERENCES EMPLEADO(DNI_EMPLEADO),
FUNCION VARCHAR(50) CHECK (FUNCION IN ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA'))
primary key (COD_PUB, DNI_EMPLEADO, FUNCION)
);
