USE [2.2 SEM 12]
CREATE TABLE RECINTO(
COD_RECINTO VARCHAR(50) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
ÇIUDAD VARCHAR(50) NOT NULL,
TELEFONO INT NOT NULL,
HORARIO TIME NOT NULL
);

CREATE TABLE ESPECTACULOS(
COD_ESPECTACULO VARCHAR(50) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
FECHA_INICIAL DATE NOT NULL,
FECHA_FINAL DATE NOT NULL,
INTERPRETE VARCHAR(50) NOT NULL,
COD_RECINTO VARCHAR(50) REFERENCES RECINTO(COD_RECINTO)
);
CREATE TABLE ZONAS_RECINTOS (
COD_RECINTO VARCHAR(50) REFERENCES RECINTO(COD_RECINTO),
ZONA VARCHAR(50) , 
CAPACIDAD INT NOT NULL,
PRIMARY KEY (COD_RECINTO, ZONA)
);
CREATE TABLE ASIENTOS (
COD_RECINTO VARCHAR(50) REFERENCES RECINTO(COD_RECINTO), 
ZONA VARCHAR(50), 
FILA INT NOT NULL, 
NUMERO INT NOT NULL,
FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);

CREATE TABLE REPRESENTACIONES (
COD_ESPECTACULO VARCHAR(50) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
FECHA DATE NOT NULL,
HORA TIME NOT NULL
);

CREATE TABLE ESPECTADORES (
DNI_CLIENTE VARCHAR(50) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(50),
CIUDAD VARCHAR(50),
NTARJETA INT NOT NULL,
);

CREATE TABLE PRECIOS_ESPECTACULOS(
COD_ESPECTACULO VARCHAR(50) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
COD_RECINTO VARCHAR(50) REFERENCES RECINTO(COD_RECINTO),
ZONA VARCHAR(50),
PRECIO INT,
FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);
CREATE TABLE ENTRADAS (
COD_ESPECTACULO VARCHAR(50) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
FECHA DATE NOT NULL,
HORA TIME NOT NULL,
COD_RECINTO VARCHAR(50) REFERENCES RECINTO(COD_RECINTO),
FILA INT,
NUMERO INT,
ZONA VARCHAR(50),
DNI_CLIENTE VARCHAR(50) REFERENCES ESPECTADORES(DNI_CLIENTE),
FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);
